- job:
    name: cinderclient-dsvm-functional
    parent: legacy-dsvm-base
    run: playbooks/legacy/cinderclient-dsvm-functional/run.yaml
    post-run: playbooks/legacy/cinderclient-dsvm-functional/post.yaml
    timeout: 4200
    voting: false
    required-projects:
      - openstack-infra/devstack-gate
      - openstack/cinder
      - openstack/python-cinderclient
    irrelevant-files:
      - ^.*\.rst$
      - ^doc/.*$
      - ^releasenotes/.*$

- project:
    templates:
      - check-requirements
      - lib-forward-testing
      - lib-forward-testing-python3
      - openstack-cover-jobs
      - openstack-lower-constraints-jobs
      - openstack-python-jobs
      - openstack-python36-jobs
      - openstack-python37-jobs
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
    check:
      jobs:
        - cinderclient-dsvm-functional
        - openstack-tox-pylint:
            voting: false
